postgres:
  restart: always
  image: postgres:latest
  volumes:
    - ./docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    - /var/lib/postgresql/data
  ports:
    - "5432:5432"
